name: Wheels

on:
  push:
    branches:
    - master
    tags:
    - 'v*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macOS-11]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - uses: docker/setup-qemu-action@v2
        if: runner.os == 'Linux'
        with:
          platforms: all

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_ALL: sh build.sh
          CIBW_ENVIRONMENT: LIBGIT2_VERSION=1.5.1 LIBSSH2_VERSION=1.10.0 OPENSSL_VERSION=3.0.8 LIBGIT2=/project/ci
          CIBW_ENVIRONMENT_MACOS: LIBGIT2_VERSION=1.5.1 LIBSSH2_VERSION=1.10.0 DYLD_LIBRARY_PATH=/usr/local/lib OPENSSL_VERSION=3.0.8
          CIBW_SKIP: "*-musllinux*"
          CIBW_MANYLINUX_AARCH64_IMAGE: "manylinux_2_24"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_24"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "LD_LIBRARY_PATH=/project/ci/lib auditwheel repair -w {dest_dir} {wheel}"
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: "DYLD_LIBRARY_PATH=/usr/local/lib delocate-listdeps {wheel} && DYLD_LIBRARY_PATH=/usr/local/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}"
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_ARCHS_LINUX: x86_64 aarch64

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [build_wheels]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/download-artifact@v4.1.7
      with:
        name: wheels
        path: dist

    - name: Display structure of downloaded files
      run: ls -lh dist

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
